description: "Evaluating the Representation Space of Diffusion Models via Self-Supervised Principles"
url: "https://heimine.github.io/"
baseurl: "/Diffusion_ICR_REP"
repository: "heimine/Diffusion_ICR_REP"

remote_theme: "mmistakes/minimal-mistakes"
minimal_mistakes_skin: "air"   # try: "air", "dark", "mint", "sunrise"

plugins:
  - jekyll-include-cache

markdown: kramdown
kramdown:
  input: GFM
  math_engine: mathjax

author:
  name: "Xiao Li"

defaults:
  - scope:
      path: ""
    values:
      layout: single
      classes: wide
      toc: false
      toc_sticky: false
